# Generated by Django 3.1.7 on 2021-03-14 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('production_year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('cubic_capacity', models.IntegerField()),
                ('horse_power', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('benzyna', 'Benzyna'), ('diesel', 'Diesel'), ('LPG', 'Lpg')], max_length=7)),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(upload_to='')),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('is_publicated', models.BooleanField(blank=True, default=False)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
